package problems;

/**
 * Problem 2 - Even Fibonacci numbers
 * <p>
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 * <p>
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * <p>
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 */
public class Problem2 {

    public static void main(String[] args) {
        int previous = 0;
        int current = 1;
        long evenValuedSum = 0;
        int next;

        while (current < 4_000_000) {
            if (current % 2 == 0) {
                evenValuedSum += current;
            }
            next = previous + current;
            previous = current;
            current = next;
        }

        System.out.println("Sum of the even-valued terms is " + evenValuedSum);
    }
}
